name: model_train
permissions:
  id-token: write
  contents: write

on:
  - push

jobs:
  run:
   runs-on:
     - ubuntu-latest
   steps:
     - uses: iterative/setup-cml@v3
     - uses: actions/checkout@v3
     - name: train model
       env :
         REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       run: |
         pip install -r requirements.txt
         python train_model.py
         python test.py

         echo "# Sanity Checks" > report2.md
         cat text.txt >> report2.md


         echo "# RF and LR Model Score" > report.md
         cat scores.txt >> report.md

         echo "# Confusion Matrix & Feature Importance" > reportl.md
         echo '![](./ConfusionMatrix.png "ConfusionMatrix")' >> reportl.md
         echo '![](./FeatureImportance.png "FeatureImportance")' >> reportl.md

         cat report2.md report.md reportl.md > combined_file.md
         cml comment create combined_file.md
